modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/BlueSheep2804/JATiCA/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://github.com/BlueSheep2804/JATiCA"
logoFile="icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jaopca"
mandatory = true
versionRange = "[4.4.13.23,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.11.1.158,)"
ordering = "NONE"
side = "BOTH"
